[general]
ignore_patterns = [
    '^\.git/',
    "^vendor/",
    '_test\.go$',
]
exclude_dirs = [
    "vendor",
    "node_modules",
    "build",
    "dist",
]

[rules.syntax]
enabled = true
max_line_length = 800

[rules.dead_code]
enabled = true
detect_unused_imports = true
detect_unused_functions = true
detect_unused_variables = true

[rules.style]
enabled = true
enforce_camel_case = true
space_after_control_statements = true
enforce_consistent_naming = true

[rules.architecture]
enabled = true
enforce_package_boundaries = true
detect_circular_dependencies = true
