# fly.toml app configuration file generated for goalandingpagenew-misty-fog-4381 on 2025-04-13T14:54:39-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'goalandingpagenew-misty-fog-4381'
primary_region = 'mia'

[build]

[env]
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
